### ISSUE TITLE
Document count should be abbreviated

### ISSUE THREAD

**Issue by MikeGoldsmith** [Couchbase-Ecosystem/VSCode-Couchbase#28]
**Is your feature request related to a problem? Please describe.**
The document count for a collection should be abbreviated for larger numbers.

For example, 1k, 100k, 1m, etc

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

_Please delete paragraphs that you did not use before submitting._

**Comment by deniswsrosa** [comment]
until 999 we show the unabbreviated version. After that we can show 1k-> 1000, 1.1k -> 1100, 1.2k -> 1230 (count doesn't need to be precise)
