### ISSUE TITLE
Named Parameters Only Support String Input

### ISSUE THREAD

**Issue by amfrye777** [Couchbase-Ecosystem/VSCode-Couchbase#411]
**Describe the bug**
Named Parameters only allow String inputs. We should be able to put any type of data: String, number, array, object...

**Steps to reproduce**
.cbNamedParams.properties file:
```
testStr=Hello
testNum=1234
testObj={"testObj": "Hello"}
testArr=[1,2,"3","4",[5]]
```
```
SELECT $testStr as testStr,$testNum as testNum,$testObj as testObj,$testArr as testArr
```
**What did you expect to see?**
correctly represented data types

**What did you see instead?**
everything formatted as strings. 

<img width="334" alt="2024-07-29_11-07-34" src="https://github.com/user-attachments/assets/a6711551-b2c3-4593-864d-cc959142739d">

**Comment by prajwal-pai77** [comment]
Hey, Thanks for reporting the bugs, we are working on fixing this and release this.

**Comment by prajwal-pai77** [comment]
We have fixed this bug in the latest release. Thanks!
