### ISSUE TITLE
Table Result View Does not show all data

### ISSUE THREAD

**Issue by amfrye777** [Couchbase-Ecosystem/VSCode-Couchbase#412]
**Describe the bug**
Certain types of queries cannot display all results 

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Two Queries:
```
select ARRAY_CONCAT(
    [{"Test": "TestValue"},{"Test": "TestValue2"}],
    [{"Test2": "Test2Value"},{"Test2": "Test2Value2"}]
) as concatArrays
```
```
select concatArrays.* 
FROM ARRAY_CONCAT(
    [{"Test": "TestValue"},{"Test": "TestValue2"}],
    [{"Test2": "Test2Value"},{"Test2": "Test2Value2"}]
) as concatArrays
```

**What did you expect to see?**
I have attached the CB query workbench console compared to vsCode output to show the resulting behavior
<img width="457" alt="2024-07-29_11-30-03" src="https://github.com/user-attachments/assets/a49524d3-ba69-4662-8910-04f35b71c6f6">
<img width="400" alt="2024-07-29_11-30-33" src="https://github.com/user-attachments/assets/31b5ae26-7def-4d7b-bd8b-7c72742e4088">

**Comment by prajwal-pai77** [comment]
We have fixed this bug in the latest release. Thanks!
