### ISSUE TITLE
Services are not detected if they are not part of 1st node

### ISSUE THREAD

**Issue by lokesh-couchbase** [Couchbase-Ecosystem/VSCode-Couchbase#414]
As Couchbase is a Multi-dimensional, multi-node cluster, It's required that we support services that are configured in other nodes and not just 1st node. 

For a cluster setup like
![image](https://github.com/user-attachments/assets/93cb2042-0320-43ec-b7a7-43de189bf1c3)

We are getting the following information inside the extension.
![image](https://github.com/user-attachments/assets/0e322814-a047-44cb-9810-1f82f556748d)

We will require to fix this so that all nodes are considered.

Reported by @rekha.nair

**Comment by prajwal-pai77** [comment]
We have fixed this bug in the latest release. Thanks!
