### ISSUE TITLE
Add "EXPLAIN" Button

### ISSUE THREAD

**Issue by Fujio-Turner** [Couchbase-Ecosystem/VSCode-Couchbase#423]
When I'm debugging a query I need to see if the crazy query I just type will RUN and/or use the new index before waiting 10-75 seconds to know its "Bad" .   next to the RUN  play button have a "Explain" button

**Comment by prajwal-pai77** [comment]
Hey, thanks for the suggestion, added a explain button next to the run query button in the latest release.
