### ISSUE TITLE
N1QL/SQL++ Pretty Print / Format

### ISSUE THREAD

**Issue by Fujio-Turner** [Couchbase-Ecosystem/VSCode-Couchbase#424]
SQL++ can get big need a why to understand the query better.

Check out this JS library to format SQL string to pretty print version.

PS. Already has support for N1QL 

https://github.com/sql-formatter-org/sql-formatter

**Comment by prajwal-pai77** [comment]
Hey, thanks, found this formatter to be pretty good, have updated it to use this.
