### ISSUE TITLE
Query Workbench crashes

### ISSUE THREAD

**Issue by dangrieshaber** [Couchbase-Ecosystem/VSCode-Couchbase#431]
Executing any query or explain causes a fatal issue in the Query Workbench when connected to a Couchbase Server Community Edition cluster, but works with a Capella connection.  
It seems to fail when trying to render results as syntax error are being displayed correctly:
![image](https://github.com/user-attachments/assets/e20d52bb-b615-4984-890c-a350257c1123)

![image](https://github.com/user-attachments/assets/5ea55ee5-e293-4deb-9557-454a5a0048fd)

Queries in the SQL++ Notebook works as expected.

Tested with multiple prior versions of the extension and the behaviour is the same.

No exceptions, logs or any other information is displayed

VSCode Version: Version: 1.94.2
CB Server: 7.6.2 Community Edition

**Comment by deniswsrosa** [comment]
Thanks for the feedback, we will work on a fix asap

**Comment by prajwal-pai77** [comment]
Hey,
Thank you for reporting this bug. We realised that this exists only in the community edition.  We are also aware that for some reason the Plan tab is empty after the query is successful, and we will take a look at this.

We have released a new version of the extension( v2.1.8) which renders the results as expected and the queries should work as expected. Please let us know if you face any difficulty after updating to new version.
Thanks!

**Comment by dangrieshaber** [comment]
Awesome, thank you very much. It's working great!
